### ISSUE TITLE
Typo in PT-BR translation is causing a fatal error when clicking on the "Post types" settings tab

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#567]
Error when clicking on “Post Type” the user reported the following error:

There is a critical error on your website. Check your email for instructions.
Learn more about how to troubleshoot WordPress issues.

>Debug message:
Fatal error: Uncaught ValueError: Unknown format specifier “n” in /home/user/public_html/wp-content/plugins/post-expirator/src/Modules/Settings/Controllers/Controller.php:220 Stack trace: #0 /home/user/public_html/wp-content/plugins/post-expirator/src/Modules/Settings/Controllers/Controller.php(220): sprintf(‘Defina o desloc…’, ‘<a href=”https:…’, ‘<code>’, ‘</code>’, ‘<code>’, ‘</code>’, ‘<code>’, ‘</code>’) #1 /home/user/public_html/wp-includes/class-wp-hook.php(324): PublishPress\Future\Modules\Settings\Controllers\Controller->onAdminEnqueueScript(‘toplevel_page_p…’) #2 /home/user/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #3 /home/user/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 /home/user/public_html/wp-admin/admin-header.php(118): do_action(‘admin_enqueue_s…’, ‘toplevel_page_p…’) #5 /home/user/public_html/wp-admin/admin.php(239): require_once(‘/home/user…’) #6 {main} thrown in /home/user/public_html/wp-content/plugins/post-expirator/src/Modules/Settings/Controllers/Controller.php on line 220

**Comment by andergmartins** [comment]
Users that have this issue can try replacing the file `languages/post-expirator-pt_BR.mo` with the following file:

[post-expirator-pt_BR.mo.zip](https://github.com/publishpress/PublishPress-Future/files/13339228/post-expirator-pt_BR.mo.zip)
